/* Calendario de fiestas. Fechas consultadas el 5 de octubre de 2026.
   Las fechas móviles (carnaval, fines de semana) cambian cada año:
   la ficha lo dice y pide confirmar. `ficha` enlaza con un lugar del mapa. */
'use strict';
(() => {
  const multi = (es, en, pt) => ({ es, en, pt });
  const fuente = (titulo, url) => ({ titulo, url });
  window.FIESTAS = [
    { id: 'enero-tilcareno', meses: [1], region: 'quebrada', lugar: 'Tilcara',
      nombre: 'Enero Tilcareño',
      cuando: multi('Todo enero', 'All of January', 'Todo janeiro'),
      descripcion: multi('Un mes de festivales, talleres y circuitos, con la plaza Álvarez Prado y los museos como centro.',
        'A month of festivals, workshops and outings, centred on Álvarez Prado square and the museums.',
        'Um mês de festivais, oficinas e passeios, com a praça Álvarez Prado e os museus como centro.'),
      fuente: fuente('Todo Jujuy · Enero Tilcareño 2026', 'https://www.todojujuy.com/el-lanzamiento-oficial-del-enero-tilcareno-2026-ya-tiene-fecha-n283496') },
    { id: 'carnaval', meses: [1, 2, 3], region: 'quebrada', lugar: 'Humahuaca, Tilcara, Maimará, Uquía, Purmamarca',
      nombre: 'Carnaval de la Quebrada', ficha: 'qu-o-carnaval',
      cuando: multi('De enero a marzo; el desentierro, el sábado de carnaval. El 7 de febrero, Día del Carnavalito.',
        'January to March; the unearthing on carnival Saturday. 7 February is Carnavalito Day.',
        'De janeiro a março; o desenterro, no sábado de carnaval. 7 de fevereiro, Dia do Carnavalito.'),
      descripcion: multi('Comparsas, coplas, harina y albahaca. Reservar alojamiento con mucha anticipación.',
        'Troupes, coplas, flour and basil. Book lodging well ahead.',
        'Comparsas, coplas, farinha e manjericão. Reserve hospedagem com muita antecedência.'),
      fuente: fuente('Visit Argentina · Carnaval de Humahuaca', 'https://www.argentina.travel/en/activities/carnaval-de-humahuaca') },
    { id: 'pachamama', meses: [8], region: null, lugar: 'Purmamarca, Tumbaya, Valle Grande y toda la Puna',
      nombre: 'Mes de la Pachamama',
      cuando: multi('Desde el 1 de agosto, todo el mes', 'From 1 August, all month', 'De 1º de agosto, o mês todo'),
      descripcion: multi('Las familias y comunidades alimentan a la Madre Tierra en la corpachada. Es una ceremonia: si te invitan, se acompaña con respeto y sin fotos que no se hayan pedido.',
        'Families and communities feed Mother Earth in the corpachada. It is a ceremony: if invited, join respectfully and ask before taking photos.',
        'Famílias e comunidades alimentam a Mãe Terra na corpachada. É uma cerimônia: se for convidado, acompanhe com respeito e peça antes de fotografar.'),
      fuente: fuente('Todo Jujuy · Agosto, mes de la Pachamama', 'https://www.todojujuy.com/jujuy/agosto-mes-la-pachamama-una-tradicion-que-se-transmite-generaciones-n123911') },
    { id: 'vincha', meses: [8], region: 'puna', lugar: 'Casabindo', nombre: 'Toreo de la Vincha', ficha: 'pu-03',
      cuando: multi('15 de agosto', '15 August', '15 de agosto'),
      descripcion: multi('Fiesta de la Virgen de la Asunción: misa, procesión con sikuris y, a la tarde, el toreo, donde se le quita al toro una vincha con monedas sin lastimarlo.',
        'Feast of Our Lady of the Assumption: mass, procession with sikuris and, in the afternoon, the bullfight where a coin headband is taken from the bull without harming it.',
        'Festa da Virgem da Assunção: missa, procissão com sikuris e, à tarde, o toreio, em que se tira do touro uma faixa com moedas sem machucá-lo.'),
      fuente: fuente('Todo Jujuy · Casabindo vive el Toreo de la Vincha', 'https://www.todojujuy.com/tras-las-honras-la-virgen-la-asuncion-casabindo-ya-vive-el-tradicional-toreo-la-vincha-n294677') },
    { id: 'exodo', meses: [8], region: 'valles', lugar: 'San Salvador de Jujuy', nombre: 'Éxodo Jujeño',
      cuando: multi('22 y 23 de agosto', '22 and 23 August', '22 e 23 de agosto'),
      descripcion: multi('Se recuerda el éxodo de 1812 con la marcha evocativa por el centro y la quema simbólica. Ese día Jujuy es capital honoraria del país.',
        'The 1812 exodus is remembered with a march through downtown and a symbolic burning. That day Jujuy is the country\'s honorary capital.',
        'Lembra-se o êxodo de 1812 com a marcha pelo centro e a queima simbólica. Nesse dia Jujuy é capital honorária do país.'),
      fuente: fuente('Todo Jujuy · Aniversario del Éxodo Jujeño', 'https://www.todojujuy.com/jujuy/213-aniversario-del-exodo-jujeno-cronograma-completo-marcha-quema-y-desfile-n278329') },
    { id: 'santa-rosa', meses: [8], region: 'quebrada', lugar: 'Purmamarca', nombre: 'Fiesta de Santa Rosa de Lima',
      ficha: 'qu-o-santarosa',
      cuando: multi('Fines de agosto', 'Late August', 'Fim de agosto'),
      descripcion: multi('La fiesta patronal de Purmamarca, con misa central y procesión.',
        'Purmamarca\'s patron saint festival, with mass and procession.',
        'A festa padroeira de Purmamarca, com missa e procissão.'),
      fuente: fuente('Todo Jujuy · Purmamarca celebra a Santa Rosa de Lima', 'https://www.todojujuy.com/purmamarca-celebra-santa-rosa-lima-cronograma-completo-y-misa-central-n295157') },
    { id: 'estudiantes', meses: [9], region: 'valles', lugar: 'San Salvador de Jujuy · Ciudad Cultural',
      nombre: 'Fiesta Nacional de los Estudiantes',
      cuando: multi('Fines de septiembre, unos diez días', 'Late September, about ten days', 'Fim de setembro, uns dez dias'),
      descripcion: multi('Desfile de carrozas de papel, flores y luces que arman los colegios, con música y baile.',
        'Parade of floats made by schools from paper, flowers and lights, with music and dance.',
        'Desfile de carros alegóricos de papel, flores e luzes feitos pelas escolas, com música e dança.'),
      fuente: fuente('Todo Jujuy · Historia de la FNE', 'https://www.todojujuy.com/historia-la-fne-cuando-y-como-surgio-la-fiesta-nacional-los-estudiantes-n278757') },
    { id: 'manka', meses: [10], region: 'puna', lugar: 'La Quiaca', nombre: 'Manka Fiesta', ficha: 'pu-o-manka',
      cuando: multi('Tercer fin de semana de octubre', 'Third weekend of October', 'Terceiro fim de semana de outubro'),
      descripcion: multi('La fiesta de las ollas: trueque de ollas de barro, sal, lana y alimentos entre la Puna y el sur de Bolivia.',
        'The pot festival: barter of clay pots, salt, wool and food between the Puna and southern Bolivia.',
        'A festa das panelas: troca de panelas de barro, sal, lã e alimentos entre a Puna e o sul da Bolívia.'),
      fuente: fuente('Todo Jujuy · Manka Fiesta', 'https://www.todojujuy.com/jujuy/la-quiaca-comenzo-la-manka-fiesta-n241033') }
  ];
})();
